__author__ = 'alexy'

INSTALLED_APPS = (
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'imagekit',
    'widget_tweaks',
    'annoying',
    'inplaceeditform_bootstrap',
    'inplaceeditform',
    'ckeditor',
    'core',
    'apps.ticket',
    'apps.travel',
    'apps.group',
    'apps.excurse',
    'apps.landing',
    'apps.about',
    'apps.faq',
)
